version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.3.0
    - 1.3.1
    - 1.3.2
  - dependency-name: androidx.lifecycle:lifecycle-runtime-ktx
    versions:
    - 2.3.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
  - dependency-name: com.google.appengine:appengine-endpoints
    versions:
    - 1.9.84
  - dependency-name: com.google.appengine:appengine-endpoints-deps
    versions:
    - 1.9.84
